#ifndef CONFIG_H
#define CONFIG_H

/*** Do not edit this file. This file is autogenerated via CMake. ***/

/* definition of relative path to test images */
#define PATH_ASSETS "/Users/tzaman/Dropbox/code/rti/assets/"

/* definition of relative path to ps kernel */
#define PATH_KERNELS "/Users/tzaman/Dropbox/code/rti/src/"

/* hardware configuration using third LED as start */
#define START_LED 3

/* image dimensions */
#define IMG_HEIGHT 480
#define IMG_WIDTH 640

#endif
